name: stack-dev-helpers

networks:
  my-network-proxy:
    name: my-network-proxy
    external: true

volumes:
  backup:

services:
  cyberchef:
    image: ghcr.io/gchq/cyberchef:10.19.4
    restart: unless-stopped
    networks:
      - my-network-proxy
    expose:
      - 80
    labels:
      virtual.caddyfile: |
        http://cyberchef.dev.localhost {
          reverse_proxy cyberchef:80 {
          }
        }
      virtual.homefile: |
        <div>
          <a class="shadow" href="http://cyberchef.dev.localhost">cyberchef</a>
          <small>http://cyberchef.dev.localhost</small>
        </div>

  cloudbeaver:
    image: dbeaver/cloudbeaver:25.2.0
    restart: unless-stopped
    networks:
      - my-network-proxy
    expose:
      - 8978
    volumes:
      - /var/mnt-links/docker/cloudbeaver/opt/cloudbeaver/workspace:/opt/cloudbeaver/workspace
      - /var/mnt-links/media/user-share:/mnt/user-share:rw
    labels:
      virtual.caddyfile: |
        http://cloudbeaver.dev.localhost {
          reverse_proxy cloudbeaver:8978 {
          }
        }
      virtual.homefile: |
        <div>
          <a class="shadow" href="http://cloudbeaver.dev.localhost">cloudbeaver</a>
          <small>http://cloudbeaver.dev.localhost</small>
        </div>

  pgadmin:
    image: dpage/pgadmin4:9.8.0
    restart: always
    user: root
    networks:
      - my-network-proxy
    expose:
      - 80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin
      PGADMIN_DEFAULT_PASSWORD: r74Qsg7jdwUfryM
    volumes:
      - /var/mnt-links/docker/pgadmin/var/lib/pgadmin:/var/lib/pgadmin
    labels:
      virtual.caddyfile: |
        http://pgadmin.dev.localhost {
          reverse_proxy http://pgadmin:80 {
          }
        }
      virtual.homefile: |
        <div>
          <a class="shadow" href="http://pgadmin.dev.localhost">pgadmin</a>
          <small>http://pgadmin.dev.localhost</small>
        </div>
