name: stack-media-torbrowser

networks:
  my-network-proxy:
    name: my-network-proxy
    external: true

services:
  torbrowser:
    image: domistyle/tor-browser:14.5.5
    restart: no
    shm_size: 2gb
    hostname: torbrowser.media.localhost
    networks:
      - my-network-proxy
    expose:
      - 5800
    environment:
      VNC_PASSWORD: 
      WEB_AUDIO: 1
      WEB_FILE_MANAGER: 1
      DARK_MODE: 1
      # DISPLAY_WIDTH: 1920
      # DISPLAY_HEIGHT: 1080
      KEEP_APP_RUNNING: 1
      TZ: Europe/Vienna
    labels:
      virtual.caddyfile: |
        http://torbrowser.media.localhost {
          reverse_proxy http://torbrowser:5800 {
          }
        }
      virtual.homefile: |
        <div>
          <a class="shadow" href="http://torbrowser.media.localhost?resize=remote">tor browser</a>
          <small>http://torbrowser.media.localhost</small>
        </div>
