name: stack-llm-ollama

networks:
  my-network-proxy:
    name: my-network-proxy
    external: true

services:
  ollama:
    image: ollama/ollama:0.11.8
    restart: always
    networks:
      - my-network-proxy
    expose:
      - 11434
    ports:
      - 11434:11434
    volumes:
      - /var/mnt-links/docker/ollama/root/.ollama:/root/.ollama
